MVC_Project/Models/Continents.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;

namespace MVC_Project.Models
{
    public class Continents
    {
        [Key]
        public int  ContinentID { get; set; }
        public string ContinentName { get; set; }
        public virtual ICollection<Countries> CountriesList { get; set; }
        public virtual ICollection<Travellers> travellerslist {get; set;}
    }

     
}

MVC_Project/Models/Countries.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC_Project.Models
{
    public class Countries
    {
        [Key]
        public int ID { get; set; }
        public string countryname { get; set; }
        public string currencyname { get; set; }
        public double conversionrate { get; set; }
        public int? fkcontinent { get; set; }        
        public virtual ICollection<Travellers> travellerslist { get; set; }        
        public virtual Continents continent {get; set;}
    }
}

MVC_Project/Models/Travellers.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVC_Project.Models
{
    public class Travellers 
    {
        [Key]
        public int ID { get; set; }
        [StringLength(20, ErrorMessage="First name too long")]
        [Required]
        public string firstname { get; set; }        
        [StringLength(30, ErrorMessage="Last name too long")]
        public string lastname { get; set; }
        public string countryvisited { get; set; }
        [Range(0,5)]
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:F2}")]
        public double rating { get; set; }
        [StringLength(300, ErrorMessage="Comment text too long")]
        public string comments { get; set; }
        public int fkcountriesid { get; set; }
        public int fkcontinentalid { get; set; }
        public virtual Continents continent { get; set; }
        public virtual Countries country { get; set; }
        
    }
}

MVC_Project/Models/WorldContext.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Mvc;
using System.Web.Security;
using MVC_Project.Models;
using System.Data.Entity.ModelConfiguration.Conventions;

namespace MVC_Project.EFData
{
    public class WorldContext : DbContext
    {
        public DbSet<Continents> continents { get; set; }
        public DbSet<Countries> countries { get; set; }
        public DbSet<Travellers> travellers { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();           
            modelBuilder.Entity<Countries>().HasOptional(a => a.continent).WithMany(b=>b.CountriesList).HasForeignKey(a=>a.fkcontinent);
            modelBuilder.Entity<Travellers>().HasRequired(c => c.continent).WithMany(d => d.travellerslist).HasForeignKey(c => c.fkcontinentalid);
            modelBuilder.Entity<Travellers>().HasRequired(e => e.country).WithMany(f => f.travellerslist).HasForeignKey(e=>e.fkcountriesid);
        }
    }

   
}

MVC_Project/Controllers/ContinentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Project.EFData;

namespace MVC_Project.Controllers
{
    public class ContinentsController : Controller
    {
        //
        // GET: /Continents/
        private WorldContext w = new WorldContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult continents()
        {
            return View(w.continents.ToList());
        }

    }
}

MVC_Project/Controllers/CountriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Project.EFData;
using MVC_Project.Models;

namespace MVC_Project.Controllers
{
    public class CountriesController : Controller
    {
        //
        // GET: /Countries/
        private WorldContext w = new WorldContext();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult countries()
        {
            return View(w.countries.ToList());
        }
        public ActionResult details(int id)
        {
            Countries country = w.countries.Find(id);
            return View(country);
        }
        public ActionResult countriesindex(int id)
        {
            Continents c = w.continents.Find(id);
            return View(c);
        }
        public ActionResult addcountry()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post), ActionName("addcountry")]
        public ActionResult addcountry(Countries c)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (w.countries.Where(d => d.countryname == c.countryname).SingleOrDefault() != null)
            {
                ViewBag.err = "Duplicate exists";
                return View();
            }
            w.countries.Add(c);
            w.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

    }
}

MVC_Project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Project.Models;
using MVC_Project.EFData;

namespace MVC_Project.Controllers
{
    public class HomeController : Controller
    {
        private WorldContext w = new WorldContext();

        public ActionResult Index()
        {
            return View(w.continents.ToList());
        }
       

        

        

        

        
       

        
    }
}

MVC_Project/Controllers/TravellersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC_Project.EFData;
using MVC_Project.Models;

namespace MVC_Project.Controllers
{
    public class TravellersController : Controller
    {
        //
        // GET: /Travellers/
        private WorldContext w = new WorldContext();
        public ActionResult Index()
        {
   
            return View(w.travellers.ToList());
        }
        public ActionResult addtravellers()
        {
            return View();
        }

        [AcceptVerbs(HttpVerbs.Post), ActionName("addtravellers")]
        public ActionResult addtravellers(Travellers t)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            w.travellers.Add(t);
            w.SaveChanges();
            return RedirectToAction("Index","Home");
        }

    }
}

MVC_Project/Views/Continents/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MVC_Project/Views/Continents/continents.cshtml
@model IEnumerable<MVC_Project.Models.Continents>
@{
    ViewBag.Title = "Continents";
}

<h2>Continents</h2>
<table>
    <tr>
        <td>Continent Name</td>
        <td>Countries Count</td>
        <td>Travellers Count</td>
        <td></td>
    </tr>
@foreach (var x in Model)
{
    <tr>
        <td>@Html.ActionLink(x.ContinentName, "countriesindex", "Continents",new { id = x.ContinentID },null)</td>
        <td>@Html.DisplayFor(modelItem => x.CountriesList.Count)</td>
        <td>@Html.DisplayFor(modelItem => x.travellerslist.Count)</td>
        <td>@Html.ActionLink("Add Country","addcountry", "Countries", new {fkcontinent = x.ContinentID},null)</td>
    </tr>
}
</table>

MVC_Project/Views/Countries/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MVC_Project/Views/Countries/addcountry.cshtml
@model MVC_Project.Models.Countries
@{
    ViewBag.Title = "Add Country";
}

<h2>Add Country</h2>
<p>@ViewBag.err</p>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
<div>
    @Html.LabelFor(x => x.countryname)
    @Html.EditorFor(x => x.countryname)
</div>
<div>
    @Html.LabelFor(x => x.conversionrate)
    @Html.EditorFor(x => x.conversionrate)
</div>
<div>
    @Html.LabelFor(x => x.currencyname)
    @Html.EditorFor(x => x.currencyname)
</div>
<p>
    <input type="submit" value="Create" />
</p>
}

MVC_Project/Views/Countries/countries.cshtml
@model IEnumerable<MVC_Project.Models.Countries>
@{
    ViewBag.Title = "Countries";
}
<h2>Countries</h2>
<table>
<tr>
    <td>Continent</td>
    <td>Country</td>
    <td>Currency</td>
    <td>Conversion Rate</td>
    <td>Travellers Count</td>
    <td></td>
</tr>
@foreach (var x in Model)
{
    <tr>
        <td>@Html.DisplayFor(modelItem => x.continent.ContinentName)</td>
        <td>@Html.ActionLink(x.countryname, "details", new { id = x.ID })</td>
        <td>@Html.DisplayFor(modelItem => x.currencyname)</td>
        <td>@Html.DisplayFor(modelItem => x.conversionrate)</td>
        <td>@Html.DisplayFor(modelItem => x.travellerslist.Count)</td>
        <td>@Html.ActionLink("Add Comment","addtravellers", "Travellers", new { fkcountriesid = x.ID, fkcontinentalid = x.continent.ContinentID},null)</td>
    </tr>    
}
</table>

MVC_Project/Views/Countries/countriesindex.cshtml
@model MVC_Project.Models.Continents
@{
    ViewBag.Title = "Countries";
}
<table>
<tr>
    <td>Country</td>
    <td>Continent</td>
    <td>Currency</td>
    <td>Conversion Rate</td>
    <td></td>
</tr>
@foreach(var x in Model.CountriesList)
{
    <tr>
        <td>@Html.ActionLink(x.countryname, "details", "Countries", new { id = x.ID },null)</td>
        <td>@Html.DisplayFor(model => x.continent.ContinentName)</td>
        <td>@Html.DisplayFor(model => x.currencyname)</td>
        <td>@Html.DisplayFor(model => x.conversionrate)</td>
        <td>@Html.ActionLink("Add Country", "addcountry", "Countries", new {fkcontinent = x.ID }, null)</td>
    </tr>
}
</table>

MVC_Project/Views/Countries/details.cshtml
@model MVC_Project.Models.Countries
@{
    ViewBag.Title = "Country";
}

<h2>@Html.DisplayFor(a=>a.countryname)</h2>
<p>@Html.DisplayFor(a => a.currencyname)</p>
<p>@Html.DisplayFor(a=>a.conversionrate)</p>

@foreach (var x in Model.travellerslist)
{
    <p>Commenter: @x.firstname @x.lastname</p>
    <p>Rating: @x.rating</p>                                                 
    <p>@x.comments</p>

}

<p>@Html.ActionLink("Back to List", "countries", "Countries")</p>

MVC_Project/Views/Home/Index.cshtml
@model IEnumerable<MVC_Project.Models.Continents>
@{
    ViewBag.Title = "Continents";
}

<h2>Continents</h2>
<table>
    <tr>
        <td>Continent Name</td>
        <td>Countries Count</td>
        <td>Travellers Count</td>
        <td></td>
    </tr>
@foreach (var x in Model)
{
    <tr>
        <td>@Html.ActionLink(x.ContinentName, "countriesindex","Countries", new { id = x.ContinentID },null)</td>
        <td>@Html.DisplayFor(modelItem => x.CountriesList.Count)</td>
        <td>@Html.DisplayFor(modelItem => x.travellerslist.Count)</td>
        <td>@Html.ActionLink("Add Country","addcountry", "Countries",new {fkcontinent = x.ContinentID}, null)</td>
    </tr>
}
</table>

MVC_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <style>
            ul li {display:inline; font-size:150%}
        </style>
    </head>
    <body>
        <header>  
        <ul style='list-style-type:none; text-align:center'>        
            <li>@Html.ActionLink("Home","Index","Home")</li>
            <li>@Html.ActionLink("Countries","countries","Countries")</li>
        </ul>    
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>

        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

MVC_Project/Views/Travellers/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MVC_Project/Views/Travellers/addtravellers.cshtml
@model MVC_Project.Models.Travellers
@{
    ViewBag.Title = "Add Travellers";
}

<h2>Add Travellers</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <div>
        @Html.LabelFor(x => x.firstname)
        @Html.EditorFor(x => x.firstname)
        @Html.ValidationMessageFor(x => x.firstname)
    </div>
    <div>
        @Html.LabelFor(x => x.lastname)
        @Html.EditorFor(x => x.lastname)
        @Html.ValidationMessageFor(x => x.lastname)
    </div>
    <div>
        @Html.LabelFor(x => x.comments)
        @Html.EditorFor(x => x.comments)
        @Html.ValidationMessageFor(x => x.comments)
    </div>
        <div>
        @Html.LabelFor(x => x.rating)
        @Html.EditorFor(x => x.rating)
        @Html.ValidationMessageFor(x => x.rating)
    </div>
    
    <p>
        <input type="submit" value="Create" />
    </p>
}